title: Philip Fradkin # your name (or website title) here
logo: "/images/Phil.jpg?raw=true" # your photo (or logo) here
email: phil.fradkin@gmail.com
description: >-
  Personal site of Philip Fradkin — PhD candidate at the University of
  Toronto working on machine learning for genomics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philechka.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: phil_fradkin
github_username:  phil-fradkin
linked_in: https://www.linkedin.com/in/philip-fradkin-330a417b/

author:
  name: Philip Fradkin
  email: phil.fradkin@gmail.com

plugins:
  - jekyll-feed